apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-grafana-config
data:
  queries.yaml: |
    sqlgd:
      database_version:
        - SELECT banner FROM v$version WHERE banner LIKE 'Oracle%'
      select_100_tblog_sqlserver:
        - |
          SELECT * 
          FROM tbLOG 
          ORDER BY LOG_DH DESC
          OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY;
      select_100_tblog_postgres:
        - |
          SELECT * FROM tbLOG ORDER BY LOG_DH DESC LIMIT 100;